def placemark_kml(placemark, filename):
    with open(filename, "w") as kml_file:
        kml_file.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                          + "<kml xmlns=\"http://www.opengis.net/kml/2.2\">\n"
                          + "\t<Document>\n"
                          + "\t\t<Style id=\"" + placemark.style_url.name.lower().replace(" ", "_") + "\">\n"
                          + "\t\t\t<IconStyle>\n"
                          + "\t\t\t\t<Icon>\n"
                          + "\t\t\t\t\t<href>" + placemark.style_url.href + "</href>\n"
                          + "\t\t\t\t\t<scale>1.0</scale>\n"
                          + "\t\t\t\t</Icon>\n"
                          + "\t\t\t</IconStyle>\n"
                          + "\t\t</Style>\n"
                          + "\t\t<Placemark>\n"
                          + "\t\t\t<name>" + placemark.name + "</name>\n"
                          + "\t\t\t<description>" + placemark.description + "</description>\n"
                          + "\t\t\t<styleUrl>" + placemark.style_url.name.lower().replace(" ", "_") + "</styleUrl>\n"
                          + "\t\t\t<Point>\n"
                          + "\t\t\t\t<altitudeMode>absolute</altitudeMode>\n"
                          + "\t\t\t\t<coordinates>"
                          + str(placemark.longitude) + "," + str(placemark.latitude) + "," + str(placemark.altitude)
                          + "</coordinates>\n"
                          + "\t\t\t</Point>\n"
                          + "\t\t</Placemark>\n"
                          +"\t</Document>\n"
                          + "</kml>")
